# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Learning/ComputerOrganization/project/code/cs202-CPU/project_1.srcs/sources_1/ip/programrom/programrom.xci
# IP: The module: 'programrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Learning/ComputerOrganization/project/code/cs202-CPU/project_1.srcs/sources_1/ip/programrom/programrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'programrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Learning/ComputerOrganization/project/code/cs202-CPU/project_1.srcs/sources_1/ip/programrom/programrom.xci
# IP: The module: 'programrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Learning/ComputerOrganization/project/code/cs202-CPU/project_1.srcs/sources_1/ip/programrom/programrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'programrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
